theme: minima
title: All about fruits
author: Sebastien Hubert
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is going to be all about vegetables, wait, I mean fruit. It's gonna about fruits. Even tomatoes.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
